### ISSUE TITLE
AES-CTR encrypt/decrypt: implement missing Crypto support

### ISSUE THREAD

**Issue by thelunararmy** [anvilresearch/webcrypto#35]
As outlined in https://www.w3.org/TR/WebCryptoAPI/#dfn-AesCtrParams : which requires the use of a counter and length parameters for use in the counter style block encryption ([More info here](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Counter_.28CTR.29)), is currently not "intuitively" supported by the node's lib Crypto https://nodejs.org/api/crypto.html#crypto_class_cipher. It has some base level implementation of `aes-128-ctr`, but does not make use of a counter at all; thus resulting in an unsupported issue complained about in nodejs/node#13801.

@EternalDeiwos pointed out https://github.com/jrnewell/crypto-aes-ctr/blob/master/lib/index.js as good alternative. Further investigation may need to be done if node doesnt support this problem.

**Comment by christiansmith** [comment]
This would be useful for implementing Ethereum/Web3 Secret Storage Definition. 

https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

**Comment by thelunararmy** [comment]
Fixed, now supported as of `0.7.0`
