### ISSUE TITLE
Openssl

### ISSUE THREAD

**Issue by adminq80** [anvilresearch/webcrypto#36]
I am working on a project that relies on this library and I ran into issues while building up Docker container for that project because `webcrypto` was returning NULL for the keys generated. After investigating the bug, I found that this library relied on `openssl` but the command line tool. I was using Node:alpine container and didn't come with `openssl` by default. 

I would like to propose to add `openssl` command checker or printing that `openssl` is not found from the code itself instead returning NULL objects.

**Comment by EternalDeiwos** [comment]
Good catch. Thank you.

**Comment by adminq80** [comment]
I just submitted a PR with a quick fix to this problem

Please review and let me know what you think.
