### ISSUE TITLE
K256 exportKey failing on node 8+

### ISSUE THREAD

**Issue by thelunararmy** [anvilresearch/webcrypto#44]
Node 8+ seemingly causes issues with `asn1.js` which has a ripple effects into `@trust/key-to` used by ECDSA exportKey (specifically K256) since it cannot interpret the notation. @EternalDeiwos and I will need to hunt down the specific problem when we get closer to swapping over to node 8.

**Comment by EternalDeiwos** [comment]
As of Node v8.5.0 this doesn't seem to be happening anymore. We'll keep an eye on it.
