### ISSUE TITLE
AES-KW

### ISSUE THREAD

**Issue by EternalDeiwos** [anvilresearch/webcrypto#45]
@thelunararmy has been trying to implement AES-KW for us but we seem to have found a bug within node itself.

I've opened an issue on their repo (nodejs/node#15009) and marking us as blocked on this for the moment.

**Comment by christiansmith** [comment]
@thelunararmy @EternalDeiwos – this was a great catch guys. Thanks for filing the issue with nodejs.

**Comment by EternalDeiwos** [comment]
Reporting node/nodejs#15037 has been merged. Hopefully we'll see a LTS patch release soon and can give this another try.

**Comment by EternalDeiwos** [comment]
The fix was included in v8.5.0 of node. Hasn't been backported to v6.x yet.

**Comment by thelunararmy** [comment]
Awesome. Will get this implemented next.

**Comment by EternalDeiwos** [comment]
Algorithm complete as of #49. Thanks @thelunararmy.
