### ISSUE TITLE
RSA-OAEP encrypt/decrypt

### ISSUE THREAD

**Issue by thelunararmy** [anvilresearch/webcrypto#46]
Node's support for `rsa-oaep` seems a little obscure since there is no clear distinction between the proper `oaep` padding and no padding. The API does indicate there to be a specific RSA PKCS1 OAEP padding flag enabler for the `publicEncrypt` and `privateDecrypt` functions within `crypto`, however upon testing the encrypted output from Chrome as input to crypto `privateDecrypt` the latter cannot decipher the cypherText.

`node-jose` has an implementation of OAES using crypto, as seen [here, line 142](https://github.com/cisco/node-jose/blob/master/lib/algorithms/rsaes.js), however this has no clear indication for the use of Label L or OAES padding.

**Comment by thelunararmy** [comment]
Seems like SHA-1 is supported. Tested and x-platform works. Hurray.

**Comment by thelunararmy** [comment]
Tested and implemented. Will rollout in next minor update.

**Comment by EternalDeiwos** [comment]
We need some unicode skulls on this... given that SHA-1 has been broken already. CC @christiansmith.
