### ISSUE TITLE
RSA-PSS support

### ISSUE THREAD

**Issue by thelunararmy** [anvilresearch/webcrypto#56]
Been looking at implementing RSA-PSS using node native, but I cannot see where to inject the salt length as outlined in https://www.w3.org/TR/WebCryptoAPI/#rsa-pss.

Furthermore, it seems that RSA-PSS support is seemingly implemented following this discussion: https://github.com/nodejs/node/issues/1127 and the  `RSA_PKCS1_PSS_PADDING` is available but there is still no direct support of using it with `crypto.privateEncrypt` or `crypto.publicDecrypt` outlined here: https://nodejs.org/api/crypto.html#crypto_crypto_privateencrypt_privatekey_buffer.
Finally, the biggest setback is no direct implementation of setting `saltLength`, they key attribute for PSS, despite  https://github.com/nodejs/node/commit/a7d4cade46e7c51d02ffbd00f0c6c32101fc85f2 commit explicitly outlining that setting the saltLength is possible.

If anyone can point out an example for me I'd be very appreciative, I'm a bit stuck with this one. 

Some external support libraries I've looked at:
- https://interledgerjs.github.io/five-bells-condition/jsdoc/crypto_rsa.js.html
- https://www.npmjs.com/package/ursa

**Comment by EternalDeiwos** [comment]
I don't think you can use RSA-PSS to do encryption/decryption -- only signing/verifying. You're meant to use it with something like `crypto.createSign('sha-256')`.

Double checked everything is working [here](https://gist.github.com/EternalDeiwos/6f88979a4ab56c9979cf0a760b0edf31).

**Comment by thelunararmy** [comment]
Right, will check. Thanks @EternalDeiwos

**Comment by thelunararmy** [comment]
Currently a PR for next version.

One quick thing to note regarding testing for `sign`: These tests will not result in matching signatures since the data is salted by a random generated salt of specified saltLength. Hence the resulting signatures will (or should) always differ Unless these is a way to specify the exact salt there is no way to consistently test this use case except through generating the signature natively, and verifying it in Chrome.
Which is manually tested before each npm release)
