### ISSUE TITLE
Implement AES-GCM algos

### ISSUE THREAD

**Issue by dmitrizagidulin** [anvilresearch/webcrypto#6]
User feature request, implement the various AES-GCM encrypt/decrypt methods.

Fortunately, these are available in node [`crypto`](https://nodejs.org/api/crypto.html).
Need to be able to:

```js
const crypto = require('crypto')

const GCM = 'id-aes128-GCM'

const cipher = crypto.createCipheriv(GCM, sendkey, sendiv)
const decipher = crypto.createDecipheriv(GCM, recvkey, recviv)
```

Relevant section in WebCrypto: https://www.w3.org/TR/WebCryptoAPI/#aes-gcm

**Comment by thelunararmy** [comment]
Supported as of 610967cc07ee4bfdbe441337e6b531e3c7944773
