### ISSUE TITLE
Implement support for Argon2 algorithm

### ISSUE THREAD

**Issue by Inkeliz** [anvilresearch/webcrypto#63]
Webcrypto already have support for PBKDF2, but it seems to be the only derivation function available until now.  Of course, we have HKDF and HMAC but it not suitable for user-input/password.

The [Argon2]( https://github.com/P-H-C/phc-winner-argon2) is the winner of [PHC]( https://password-hashing.net/). The Argon2 is used in [LibSodium](https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html) and some other softwares (like [KeePass](https://keepass.info/help/kb/kdbx_4.html#argon2)). Also we have it _natively_ available in [PHP]( http://php.net/manual/en/function.password-hash.php) and [Go]( https://godoc.org/golang.org/x/crypto/argon2) and [_bindings_](https://github.com/P-H-C/phc-winner-argon2#bindings).

Have any plan to implement Argon2 (Argon2i, Argon2d and Argon2id) as an alternative for PBKDF2 in Webcrypto?

Refereces:
-	[Argon2: the memory-hard function for password hashing and other applications]( https://github.com/P-H-C/phc-winner-argon2/raw/master/argon2-specs.pdf)
-	[Password Hashing Competition](https://password-hashing.net)

**Comment by thelunararmy** [comment]
We are currently not going to explore Argon2 at this time.

**Comment by Slapbox** [comment]
Hope to see a change of heart on this.
