### ISSUE TITLE
RSA parameter selection

### ISSUE THREAD

**Issue by EternalDeiwos** [anvilresearch/webcrypto#67]
The following code (and the same for `.verify`) should be using `this.hash.name` as the keys themselves aren't bound to a specific hash.

https://github.com/anvilresearch/webcrypto/blob/master/src/algorithms/RSASSA-PKCS1-v1_5.js#L81-L91

I tried doing a quick fix for this but it breaks all the tests.

**Comment by thelunararmy** [comment]
Woops, this should be class. Will fix.

**Comment by thelunararmy** [comment]
Fixed in 97cfbe35fff1880227c3dc3ef13ad922c6f7d5d0 , just waiting for latest merge then I'll PR it.

**Comment by EternalDeiwos** [comment]
Fixed in #69. Closing.
